<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.oTiYhdv' shared service.

return $this->privates['.service_locator.oTiYhdv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'job' => ['privates', '.errored..service_locator.oTiYhdv.App\\Entity\\Job', NULL, 'Cannot autowire service ".service_locator.oTiYhdv": it references class "App\\Entity\\Job" but no such service exists.'],
]);
