<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventListener\JobUploadListener' shared autowired service.

include_once $this->targetDirs[3].'/src/EventListener/JobUploadListener.php';
include_once $this->targetDirs[3].'/src/Service/FileUploader.php';

return $this->privates['App\EventListener\JobUploadListener'] = new \App\EventListener\JobUploadListener(new \App\Service\FileUploader(($this->targetDirs[3].'/public/uploads/jobs')));
