<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.mgqGmux' shared service.

return $this->privates['.service_locator.mgqGmux'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'job' => ['privates', '.errored..service_locator.mgqGmux.App\\Entity\\Job', NULL, 'Cannot autowire service ".service_locator.mgqGmux": it references class "App\\Entity\\Job" but no such service exists.'],
]);
