<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.TAGx9rn' shared service.

return $this->privates['.service_locator.TAGx9rn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'category' => ['privates', '.errored..service_locator.TAGx9rn.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.TAGx9rn": it references class "App\\Entity\\Category" but no such service exists.'],
    'jobHistoryService' => ['privates', 'App\\Service\\JobHistoryService', 'getJobHistoryServiceService.php', true],
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
]);
