<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.5HxYl1q' shared service.

return $this->privates['.service_locator.5HxYl1q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'affiliate' => ['privates', '.errored..service_locator.5HxYl1q.App\\Entity\\Affiliate', NULL, 'Cannot autowire service ".service_locator.5HxYl1q": it references class "App\\Entity\\Affiliate" but no such service exists.'],
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
]);
