<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventListener\AffiliateTokenListener' shared autowired service.

return $this->privates['App\EventListener\AffiliateTokenListener'] = new \App\EventListener\AffiliateTokenListener();
