<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\API\\JobController::getJobsAction' => ['privates', '.service_locator.5HxYl1q', 'get_ServiceLocator_5HxYl1qService.php', true],
    'App\\Controller\\API\\JobController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Admin\\AffiliateController::activate' => ['privates', '.service_locator.ckVO6hU', 'get_ServiceLocator_CkVO6hUService.php', true],
    'App\\Controller\\Admin\\AffiliateController::deactivate' => ['privates', '.service_locator.5HxYl1q', 'get_ServiceLocator_5HxYl1qService.php', true],
    'App\\Controller\\Admin\\AffiliateController::list' => ['privates', '.service_locator.YAqMphH', 'get_ServiceLocator_YAqMphHService.php', true],
    'App\\Controller\\Admin\\CategoryController::create' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\Admin\\CategoryController::delete' => ['privates', '.service_locator.56nF5dh', 'get_ServiceLocator_56nF5dhService.php', true],
    'App\\Controller\\Admin\\CategoryController::edit' => ['privates', '.service_locator.56nF5dh', 'get_ServiceLocator_56nF5dhService.php', true],
    'App\\Controller\\Admin\\CategoryController::list' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\Admin\\JobController::create' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\Admin\\JobController::delete' => ['privates', '.service_locator.mgqGmux', 'get_ServiceLocator_MgqGmuxService.php', true],
    'App\\Controller\\Admin\\JobController::edit' => ['privates', '.service_locator.mgqGmux', 'get_ServiceLocator_MgqGmuxService.php', true],
    'App\\Controller\\Admin\\JobController::list' => ['privates', '.service_locator.YAqMphH', 'get_ServiceLocator_YAqMphHService.php', true],
    'App\\Controller\\AffiliateController::create' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.TAGx9rn', 'get_ServiceLocator_TAGx9rnService.php', true],
    'App\\Controller\\JobController::create' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\JobController::delete' => ['privates', '.service_locator.mgqGmux', 'get_ServiceLocator_MgqGmuxService.php', true],
    'App\\Controller\\JobController::edit' => ['privates', '.service_locator.mgqGmux', 'get_ServiceLocator_MgqGmuxService.php', true],
    'App\\Controller\\JobController::list' => ['privates', '.service_locator.g8P_RSF', 'get_ServiceLocator_G8PRSFService.php', true],
    'App\\Controller\\JobController::preview' => ['privates', '.service_locator.oTiYhdv', 'get_ServiceLocator_OTiYhdvService.php', true],
    'App\\Controller\\JobController::publish' => ['privates', '.service_locator.mgqGmux', 'get_ServiceLocator_MgqGmuxService.php', true],
    'App\\Controller\\JobController::show' => ['privates', '.service_locator.eDlhsWQ', 'get_ServiceLocator_EDlhsWQService.php', true],
    'App\\Controller\\API\\JobController:getJobsAction' => ['privates', '.service_locator.5HxYl1q', 'get_ServiceLocator_5HxYl1qService.php', true],
    'App\\Controller\\API\\JobController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Admin\\AffiliateController:activate' => ['privates', '.service_locator.ckVO6hU', 'get_ServiceLocator_CkVO6hUService.php', true],
    'App\\Controller\\Admin\\AffiliateController:deactivate' => ['privates', '.service_locator.5HxYl1q', 'get_ServiceLocator_5HxYl1qService.php', true],
    'App\\Controller\\Admin\\AffiliateController:list' => ['privates', '.service_locator.YAqMphH', 'get_ServiceLocator_YAqMphHService.php', true],
    'App\\Controller\\Admin\\CategoryController:create' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\Admin\\CategoryController:delete' => ['privates', '.service_locator.56nF5dh', 'get_ServiceLocator_56nF5dhService.php', true],
    'App\\Controller\\Admin\\CategoryController:edit' => ['privates', '.service_locator.56nF5dh', 'get_ServiceLocator_56nF5dhService.php', true],
    'App\\Controller\\Admin\\CategoryController:list' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\Admin\\JobController:create' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\Admin\\JobController:delete' => ['privates', '.service_locator.mgqGmux', 'get_ServiceLocator_MgqGmuxService.php', true],
    'App\\Controller\\Admin\\JobController:edit' => ['privates', '.service_locator.mgqGmux', 'get_ServiceLocator_MgqGmuxService.php', true],
    'App\\Controller\\Admin\\JobController:list' => ['privates', '.service_locator.YAqMphH', 'get_ServiceLocator_YAqMphHService.php', true],
    'App\\Controller\\AffiliateController:create' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.TAGx9rn', 'get_ServiceLocator_TAGx9rnService.php', true],
    'App\\Controller\\JobController:create' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\JobController:delete' => ['privates', '.service_locator.mgqGmux', 'get_ServiceLocator_MgqGmuxService.php', true],
    'App\\Controller\\JobController:edit' => ['privates', '.service_locator.mgqGmux', 'get_ServiceLocator_MgqGmuxService.php', true],
    'App\\Controller\\JobController:list' => ['privates', '.service_locator.g8P_RSF', 'get_ServiceLocator_G8PRSFService.php', true],
    'App\\Controller\\JobController:preview' => ['privates', '.service_locator.oTiYhdv', 'get_ServiceLocator_OTiYhdvService.php', true],
    'App\\Controller\\JobController:publish' => ['privates', '.service_locator.mgqGmux', 'get_ServiceLocator_MgqGmuxService.php', true],
    'App\\Controller\\JobController:show' => ['privates', '.service_locator.eDlhsWQ', 'get_ServiceLocator_EDlhsWQService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
