<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_user.user_provider.username' shared service.

return $this->privates['fos_user.user_provider.username'] = new \FOS\UserBundle\Security\UserProvider(($this->services['fos_user.user_manager'] ?? $this->load('getFosUser_UserManagerService.php')));
