<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.eDlhsWQ.App\Entity\Job' shared service.

return $this->privates['.errored..service_locator.eDlhsWQ.App\Entity\Job'] = new \App\Entity\Job();
